name 'scp_packer_apps'
maintainer 'Alen Pelin'
maintainer_email 'ap@altola.co'
license 'MIT'
description 'Installs/Configures Packer Apps'
long_description 'Installs/Configures Packer Apps'
version '0.0.0'

depends 'scp_packer_w'
depends 'scp_apps'
