---
driver:
  name: vagrant
  vagrantfiles:
    - ../../../../core/chef/Vagrantfile.kitchen

provisioner:
  name: chef_solo

verifier:
  name: inspec

platforms:
  - name: w16s
    transport:
      name: winrm
    driver:
      box: scp/w16s

suites:
  - name: default
    run_list:
      - recipe[scp_windows::updates]
      - recipe[scp_vs::server]
